### ISSUE TITLE
Consul ServiceLookupThread connect to consul server get stuck

### ISSUE THREAD

**Issue by jsu216** [networknt/light-4j#1304] opened 2022-06-23 18:17 UTC
We experienced connection problem from ConsulRegistry to consul server node so that local consul registry cache could not be synchronised when service registry got updated on server side. We found this issue in one of our `light-router` instances but the implementation logic is in `light-4j`'s Consul module. This issue cannot recover by itself until restart the `light-router` instance.

We know that there is a background ServiceLookupThread that uses blocking query to consul server to get any service registration update. There is a known issue on the consul server (v 1.4.4) side that causes existing connection to consul becomes unusable and no new connection can be created to the server either. There is no report about whether the same issue could happen in new consul versions yet.

In current consul registry implementation, it waits forever for a new connection to be created to consul server without any timeout set. So if there is any problem on the consul side that stop the connection from being created, it could hang the communication from ConsulRegistry to the consul server forever.

This issue exists in both 1.6.x and 2.x branches.

**Comment by stevehu** [comment] 2022-06-24 02:03
Given our analysis, we think the issue is there is no timeout on the client-side, so if the Consul server is no response, the lookup thread will be blocked forever until we restart the server. Let's set the timeout the same as the long query and see if it can resolve the issue.

**Comment by miklish** [comment] 2022-06-28 17:38
Hi Steve, Any updates on this?

**Comment by stevehu** [comment] 2022-06-29 01:44
@miklish @jsu216 please review the PR. Thanks.

**Comment by stevehu** [comment] 2022-12-23 17:03
This issue is resolved with a total solution in https://github.com/networknt/light-4j/issues/1503

**Closed by stevehu** 2022-12-23 17:03 UTC
